### ISSUE TITLE
FileStorage list is not supported

### ISSUE THREAD

**Issue by tekrei** [this-id/flask-openapi3#16]
Hello,

I am trying to implement a multiple file upload endpoint.

I defined the file form as the following:

```
class FileForm(BaseModel):
    file: list[FileStorage]
```

And the endpoint as the following:

```
@app.post("/file/", tags=[app_tag])
def upload(form: FileForm):
    files = form.file
```

When I try to upload a file with this endpoint using Swagger, I am getting the following error:

```
[
  {
    "loc": ["file"],
    "msg": "value is not a valid list",
    "type": "type_error.list"
  }
]
```

Any suggestion on what I am doing wrong?

Thanks!

**Comment by luolingchun** [comment]
I think this is a bug and I will fix it.
